name: Auto build
on:
  push:
    branches: [ master, action-build-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # https://github.com/isaacs/node-graceful-fs/issues/192#issuecomment-779209676
          node-version: 10
      
      - run: npm i -g gitbook-cli
      
#       - run: |
#           echo $(npm root -g)/git*/node*/aproba/package.json
#           cat $(npm root -g)/git*/node*/aproba/package.json
    
      - name: Fix Gitbook install error
        run: npm install aproba@latest --save --prefix $(npm root -g)/gitbook-cli
      
      - run: gitbook install
      - run: gitbook build
      
      - name: Deploy to pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages-test
          FOLDER: _book
          MESSAGE: "Auto-build by action: {long-sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
