name: Auto build
on:
  push:
    branches: [ master, action-build-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # v14 will have error: https://blog.csdn.net/Venry_/article/details/110948703
      - name: Setup Node.js v10
        uses: actions/setup-node@v2
        with:
          node-version: 10
      
      - run: npm i -g gitbook-cli
      
      - run: gitbook install
      - run: gitbook build
      
      - name: Deploy to pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages-test
          FOLDER: _book
          MESSAGE: "Auto-build by action: {long-sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
