name: Auto build
on:
  push:
    branches: [ master, action-build-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - run: npm i -g gitbook-cli
      - run: |
          ls -al ~/.npm
          echo
          ls -al /usr/local/lib/node_modules
          echo
          which gitbook
          echo
          ls -al /opt/hostedtoolcache/node/14.18.1/x64/bin/
      
      - run: gitbook install
      - run: gitbook build
      
      - name: Deploy to pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages-test
          FOLDER: _book
          MESSAGE: "Auto-build by action: {long-sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
