name: Auto build
on:
  push:
    branches: [ master, action-build-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - run: npm i -g gitbook-cli
      
      - run: |
          echo $(npm root -g)/git*/node*/gra*/package.json
          cat $(npm root -g)/git*/node*/gra*/package.json
      
      # https://stackoverflow.com/questions/64211386/gitbook-cli-install-error-typeerror-cb-apply-is-not-a-function-inside-graceful
      - name: Fix Gitbook install error
        run: npm install graceful-fs@latest --save --prefix $(npm root -g)/gitbook-cli
      
      - run: gitbook install
      - run: gitbook build
      
      - name: Deploy to pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages-test
          FOLDER: _book
          MESSAGE: "Auto-build by action: {long-sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
